name: Flutter Analyze

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.x"
          channel: stable
          cache: true

      - name: Install package dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze
